"use client";

export interface EmojiItem {
  emoji: string;
  name: string;
  category: string;
}

export const EMOJI_CATEGORIES = [
  "faces", "gestures", "people", "animals", "food", "travel", "activities", "objects", "symbols", "flags",
];

export const EMOJIS: EmojiItem[] = [
  // Faces
  { emoji: "😀", name: "Grinning Face", category: "faces" },
  { emoji: "😂", name: "Face with Tears of Joy", category: "faces" },
  { emoji: "🥹", name: "Face Holding Back Tears", category: "faces" },
  { emoji: "😍", name: "Heart Eyes", category: "faces" },
  { emoji: "🥰", name: "Smiling with Hearts", category: "faces" },
  { emoji: "😎", name: "Cool Face", category: "faces" },
  { emoji: "🤩", name: "Star Struck", category: "faces" },
  { emoji: "😜", name: "Winking Tongue", category: "faces" },
  { emoji: "🤗", name: "Hugging Face", category: "faces" },
  { emoji: "😇", name: "Angel Face", category: "faces" },
  { emoji: "🤔", name: "Thinking Face", category: "faces" },
  { emoji: "😱", name: "Screaming Face", category: "faces" },
  { emoji: "🤯", name: "Exploding Head", category: "faces" },
  { emoji: "😈", name: "Devilish", category: "faces" },
  { emoji: "💀", name: "Skull", category: "faces" },
  { emoji: "👻", name: "Ghost", category: "faces" },
  { emoji: "🤖", name: "Robot", category: "faces" },
  { emoji: "👽", name: "Alien", category: "faces" },
  { emoji: "🎃", name: "Jack-o-Lantern", category: "faces" },
  // Gestures
  { emoji: "👍", name: "Thumbs Up", category: "gestures" },
  { emoji: "👎", name: "Thumbs Down", category: "gestures" },
  { emoji: "👏", name: "Clapping", category: "gestures" },
  { emoji: "🙌", name: "Raising Hands", category: "gestures" },
  { emoji: "💪", name: "Flexed Biceps", category: "gestures" },
  { emoji: "✌️", name: "Peace", category: "gestures" },
  { emoji: "🤙", name: "Call Me", category: "gestures" },
  { emoji: "👊", name: "Fist Bump", category: "gestures" },
  { emoji: "🖐️", name: "High Five", category: "gestures" },
  { emoji: "🤞", name: "Crossed Fingers", category: "gestures" },
  { emoji: "🫶", name: "Heart Hands", category: "gestures" },
  { emoji: "👀", name: "Eyes", category: "gestures" },
  { emoji: "💅", name: "Nail Polish", category: "gestures" },
  { emoji: "🙏", name: "Prayer", category: "gestures" },
  // People
  { emoji: "👨‍💻", name: "Developer", category: "people" },
  { emoji: "👩‍🎤", name: "Singer", category: "people" },
  { emoji: "🧑‍🎨", name: "Artist", category: "people" },
  { emoji: "👨‍🚀", name: "Astronaut", category: "people" },
  { emoji: "👩‍🏫", name: "Teacher", category: "people" },
  { emoji: "🧑‍⚕️", name: "Health Worker", category: "people" },
  { emoji: "👨‍🔧", name: "Mechanic", category: "people" },
  { emoji: "👩‍🌾", name: "Farmer", category: "people" },
  // Animals
  { emoji: "🐶", name: "Dog", category: "animals" },
  { emoji: "🐱", name: "Cat", category: "animals" },
  { emoji: "🦊", name: "Fox", category: "animals" },
  { emoji: "🐼", name: "Panda", category: "animals" },
  { emoji: "🐻‍❄️", name: "Polar Bear", category: "animals" },
  { emoji: "🦁", name: "Lion", category: "animals" },
  { emoji: "🐯", name: "Tiger", category: "animals" },
  { emoji: "🦄", name: "Unicorn", category: "animals" },
  { emoji: "🐧", name: "Penguin", category: "animals" },
  { emoji: "🐍", name: "Snake", category: "animals" },
  { emoji: "🐢", name: "Turtle", category: "animals" },
  { emoji: "🐳", name: "Whale", category: "animals" },
  { emoji: "🦋", name: "Butterfly", category: "animals" },
  { emoji: "🐝", name: "Bee", category: "animals" },
  { emoji: "🦅", name: "Eagle", category: "animals" },
  { emoji: "🐙", name: "Octopus", category: "animals" },
  // Food
  { emoji: "🍕", name: "Pizza", category: "food" },
  { emoji: "🍔", name: "Burger", category: "food" },
  { emoji: "🌮", name: "Taco", category: "food" },
  { emoji: "🍣", name: "Sushi", category: "food" },
  { emoji: "🥑", name: "Avocado", category: "food" },
  { emoji: "🍩", name: "Donut", category: "food" },
  { emoji: "🎂", name: "Birthday Cake", category: "food" },
  { emoji: "🍦", name: "Ice Cream", category: "food" },
  { emoji: "☕", name: "Coffee", category: "food" },
  { emoji: "🍺", name: "Beer", category: "food" },
  { emoji: "🥤", name: "Drink", category: "food" },
  { emoji: "🍿", name: "Popcorn", category: "food" },
  // Travel
  { emoji: "✈️", name: "Airplane", category: "travel" },
  { emoji: "🚀", name: "Rocket", category: "travel" },
  { emoji: "🏖️", name: "Beach", category: "travel" },
  { emoji: "🌋", name: "Volcano", category: "travel" },
  { emoji: "🏔️", name: "Mountain", category: "travel" },
  { emoji: "🗽", name: "Statue of Liberty", category: "travel" },
  { emoji: "🏯", name: "Castle", category: "travel" },
  { emoji: "🌊", name: "Ocean Wave", category: "travel" },
  { emoji: "🎢", name: "Roller Coaster", category: "travel" },
  { emoji: "🏝️", name: "Desert Island", category: "travel" },
  // Activities
  { emoji: "⚽", name: "Soccer", category: "activities" },
  { emoji: "🏀", name: "Basketball", category: "activities" },
  { emoji: "🎮", name: "Video Game", category: "activities" },
  { emoji: "🎵", name: "Music Note", category: "activities" },
  { emoji: "🎨", name: "Art Palette", category: "activities" },
  { emoji: "📸", name: "Camera", category: "activities" },
  { emoji: "🎤", name: "Microphone", category: "activities" },
  { emoji: "💃", name: "Dancing", category: "activities" },
  { emoji: "🏆", name: "Trophy", category: "activities" },
  { emoji: "🥇", name: "Gold Medal", category: "activities" },
  // Objects
  { emoji: "💡", name: "Light Bulb", category: "objects" },
  { emoji: "🔑", name: "Key", category: "objects" },
  { emoji: "📱", name: "Phone", category: "objects" },
  { emoji: "💻", name: "Laptop", category: "objects" },
  { emoji: "⌚", name: "Watch", category: "objects" },
  { emoji: "🎁", name: "Gift", category: "objects" },
  { emoji: "🔧", name: "Wrench", category: "objects" },
  { emoji: "📚", name: "Books", category: "objects" },
  { emoji: "✏️", name: "Pencil", category: "objects" },
  { emoji: "🧲", name: "Magnet", category: "objects" },
  // Symbols
  { emoji: "❤️", name: "Red Heart", category: "symbols" },
  { emoji: "🔥", name: "Fire", category: "symbols" },
  { emoji: "⭐", name: "Star", category: "symbols" },
  { emoji: "💯", name: "100", category: "symbols" },
  { emoji: "✅", name: "Checkmark", category: "symbols" },
  { emoji: "❌", name: "Cross Mark", category: "symbols" },
  { emoji: "☠️", name: "Skull and Crossbones", category: "symbols" },
  { emoji: "🛑", name: "Stop", category: "symbols" },
  { emoji: "🚫", name: "Prohibited", category: "symbols" },
  { emoji: "♻️", name: "Recycle", category: "symbols" },
  // Flags
  { emoji: "🏳️‍🌈", name: "Pride Flag", category: "flags" },
  { emoji: "🇺🇸", name: "USA", category: "flags" },
  { emoji: "🇬🇧", name: "UK", category: "flags" },
  { emoji: "🇫🇷", name: "France", category: "flags" },
  { emoji: "🇩🇪", name: "Germany", category: "flags" },
  { emoji: "🇯🇵", name: "Japan", category: "flags" },
  { emoji: "🇨🇳", name: "China", category: "flags" },
  { emoji: "🇧🇷", name: "Brazil", category: "flags" },
  { emoji: "🇮🇳", name: "India", category: "flags" },
  { emoji: "🇦🇺", name: "Australia", category: "flags" },
  { emoji: "🇨🇦", name: "Canada", category: "flags" },
  { emoji: "🇳🇬", name: "Nigeria", category: "flags" },
];
