import type { ExportPresetDefinition } from "@/types/export";

export const EXPORT_PRESETS: ExportPresetDefinition[] = [
  // ── Video ──
  {
    id: "youtube-1080p",
    name: "YouTube 1080p",
    platform: "YouTube",
    description: "Best quality for YouTube uploads (H.264, 1080p, 30fps)",
    icon: "▶",
    category: "video",
    popular: true,
    settings: {
      format: "mp4", videoCodec: "h264", audioCodec: "aac",
      resolution: "1080p", width: 1920, height: 1080, framerate: 30,
      videoBitrate: 12000, audioBitrate: 192, crf: 22, fastStart: true,
    },
  },
  {
    id: "youtube-4k",
    name: "YouTube 4K",
    platform: "YouTube",
    description: "Ultra HD for YouTube (H.264, 4K, 30fps)",
    icon: "▶",
    category: "video",
    popular: true,
    settings: {
      format: "mp4", videoCodec: "h264", audioCodec: "aac",
      resolution: "2160p", width: 3840, height: 2160, framerate: 30,
      videoBitrate: 45000, audioBitrate: 256, crf: 20, fastStart: true,
    },
  },
  {
    id: "youtube-60fps",
    name: "YouTube 1080p 60fps",
    platform: "YouTube",
    description: "Smooth 60fps for gaming/motion content",
    icon: "▶",
    category: "video",
    popular: false,
    settings: {
      format: "mp4", videoCodec: "h264", audioCodec: "aac",
      resolution: "1080p", width: 1920, height: 1080, framerate: 60,
      videoBitrate: 18000, audioBitrate: 192, crf: 22, fastStart: true,
    },
  },
  {
    id: "tiktok-portrait",
    name: "TikTok/Reels Portrait",
    platform: "TikTok",
    description: "Vertical 9:16 video for TikTok and Instagram Reels",
    icon: "🎵",
    category: "video",
    popular: true,
    settings: {
      format: "mp4", videoCodec: "h264", audioCodec: "aac",
      resolution: "1080p", width: 1080, height: 1920, framerate: 30,
      videoBitrate: 8000, audioBitrate: 128, crf: 23, fastStart: true,
    },
  },
  {
    id: "instagram-square",
    name: "Instagram Square",
    platform: "Instagram",
    description: "1:1 square format for Instagram feed",
    icon: "📷",
    category: "video",
    popular: true,
    settings: {
      format: "mp4", videoCodec: "h264", audioCodec: "aac",
      resolution: "1080p", width: 1080, height: 1080, framerate: 30,
      videoBitrate: 6000, audioBitrate: 128, crf: 23, fastStart: true,
    },
  },
  {
    id: "instagram-story",
    name: "Instagram Story",
    platform: "Instagram",
    description: "9:16 portrait for Instagram Stories",
    icon: "📱",
    category: "video",
    popular: false,
    settings: {
      format: "mp4", videoCodec: "h264", audioCodec: "aac",
      resolution: "1080p", width: 1080, height: 1920, framerate: 30,
      videoBitrate: 7000, audioBitrate: 128, crf: 23, fastStart: true,
    },
  },
  {
    id: "twitter-video",
    name: "Twitter/X Video",
    platform: "Twitter",
    description: "Optimized for Twitter/X timeline (H.264, 720p)",
    icon: "🐦",
    category: "video",
    popular: false,
    settings: {
      format: "mp4", videoCodec: "h264", audioCodec: "aac",
      resolution: "720p", width: 1280, height: 720, framerate: 30,
      videoBitrate: 5000, audioBitrate: 128, crf: 24, fastStart: true,
    },
  },
  {
    id: "linkedin-video",
    name: "LinkedIn Video",
    platform: "LinkedIn",
    description: "Professional format for LinkedIn",
    icon: "💼",
    category: "video",
    popular: false,
    settings: {
      format: "mp4", videoCodec: "h264", audioCodec: "aac",
      resolution: "1080p", width: 1920, height: 1080, framerate: 30,
      videoBitrate: 8000, audioBitrate: 128, crf: 23, fastStart: true,
    },
  },
  {
    id: "webm-high",
    name: "WebM High Quality",
    platform: "Web",
    description: "VP9 codec for web (smaller files, great quality)",
    icon: "🌐",
    category: "video",
    popular: false,
    settings: {
      format: "webm", videoCodec: "vp9", audioCodec: "vorbis",
      resolution: "1080p", width: 1920, height: 1080, framerate: 30,
      videoBitrate: 6000, audioBitrate: 128, crf: 25, fastStart: false,
    },
  },
  {
    id: "master-h264",
    name: "Master H.264",
    platform: "Archival",
    description: "Maximum quality H.264 for archival (large file)",
    icon: "💾",
    category: "video",
    popular: false,
    settings: {
      format: "mp4", videoCodec: "h264", audioCodec: "aac",
      resolution: "2160p", width: 3840, height: 2160, framerate: 60,
      videoBitrate: 80000, audioBitrate: 320, crf: 16, fastStart: true,
      pixelFormat: "yuv444p",
    },
  },
  {
    id: "h265-efficient",
    name: "H.265 Efficient",
    platform: "Archival",
    description: "H.265/HEVC for half the file size at same quality",
    icon: "📦",
    category: "video",
    popular: false,
    settings: {
      format: "mp4", videoCodec: "h265", audioCodec: "aac",
      resolution: "2160p", width: 3840, height: 2160, framerate: 30,
      videoBitrate: 20000, audioBitrate: 256, crf: 24, fastStart: true,
    },
  },
  {
    id: "av1-web",
    name: "AV1 Web",
    platform: "Web",
    description: "Next-gen AV1 codec — best compression (requires AV1 support)",
    icon: "🚀",
    category: "video",
    popular: false,
    settings: {
      format: "mp4", videoCodec: "av1", audioCodec: "aac",
      resolution: "1080p", width: 1920, height: 1080, framerate: 30,
      videoBitrate: 3000, audioBitrate: 128, crf: 30, fastStart: true,
    },
  },
  {
    id: "preview-draft",
    name: "Preview Draft",
    platform: "Draft",
    description: "Low resolution quick draft for review",
    icon: "📝",
    category: "video",
    popular: true,
    settings: {
      format: "mp4", videoCodec: "h264", audioCodec: "aac",
      resolution: "540p", width: 960, height: 540, framerate: 24,
      videoBitrate: 1500, audioBitrate: 96, crf: 28, fastStart: true,
    },
  },

  // ── GIF ──
  {
    id: "gif-high",
    name: "High Quality GIF",
    platform: "General",
    description: "High quality animated GIF with dithering",
    icon: "🎞",
    category: "gif",
    popular: true,
    settings: {
      format: "gif", resolution: "480p", width: 640, height: 480,
      framerate: 24, videoBitrate: 0, audioBitrate: 0, quality: 90,
      loop: 0, dither: true, includeAudio: false, sampleRate: 0, channels: 1,
      videoCodec: "h264", audioCodec: "aac", crf: 0, keyframeInterval: 250,
      pixelFormat: "yuv420p", fastStart: false, scope: "entire", includeVideo: true,
    },
  },
  {
    id: "gif-twitter",
    name: "Twitter GIF",
    platform: "Twitter",
    description: "Optimized GIF for Twitter (15MB limit)",
    icon: "🐦",
    category: "gif",
    popular: false,
    settings: {
      format: "gif", resolution: "480p", width: 480, height: 270,
      framerate: 24, quality: 70, loop: 0, dither: false, includeAudio: false,
      includeVideo: true, sampleRate: 0, channels: 1, videoBitrate: 0, audioBitrate: 0,
      videoCodec: "h264", audioCodec: "aac", crf: 23, keyframeInterval: 250,
      pixelFormat: "yuv420p", fastStart: false, scope: "entire",
    },
  },

  // ── Audio ──
  {
    id: "mp3-high",
    name: "MP3 High Quality",
    platform: "Music",
    description: "High quality MP3 (320kbps)",
    icon: "🎵",
    category: "audio",
    popular: true,
    settings: {
      format: "mp3", audioCodec: "mp3", sampleRate: 48000, channels: 2,
      audioBitrate: 320, includeVideo: false, includeAudio: true,
      resolution: "1080p", width: 1920, height: 1080, framerate: 30,
      videoBitrate: 0, videoCodec: "h264", crf: 23, keyframeInterval: 250,
      pixelFormat: "yuv420p", fastStart: false, scope: "entire",
    },
  },
  {
    id: "wav-master",
    name: "WAV Master",
    platform: "Audio",
    description: "Uncompressed WAV for professional audio",
    icon: "🎧",
    category: "audio",
    popular: false,
    settings: {
      format: "wav", audioCodec: "pcm_s16le", sampleRate: 96000, channels: 2,
      audioBitrate: 4608, includeVideo: false, includeAudio: true,
      resolution: "1080p", width: 1920, height: 1080, framerate: 30,
      videoBitrate: 0, videoCodec: "h264", crf: 23, keyframeInterval: 250,
      pixelFormat: "yuv420p", fastStart: false, scope: "entire",
    },
  },
  {
    id: "flac-lossless",
    name: "FLAC Lossless",
    platform: "Audio",
    description: "Lossless FLAC for archival audio",
    icon: "💿",
    category: "audio",
    popular: false,
    settings: {
      format: "flac", audioCodec: "flac", sampleRate: 48000, channels: 2,
      audioBitrate: 1000, includeVideo: false, includeAudio: true,
      resolution: "1080p", width: 1920, height: 1080, framerate: 30,
      videoBitrate: 0, videoCodec: "h264", crf: 23, keyframeInterval: 250,
      pixelFormat: "yuv420p", fastStart: false, scope: "entire",
    },
  },
  {
    id: "aac-podcast",
    name: "AAC Podcast",
    platform: "Podcast",
    description: "AAC optimized for spoken word",
    icon: "🎙",
    category: "audio",
    popular: false,
    settings: {
      format: "aac", audioCodec: "aac", sampleRate: 44100, channels: 1,
      audioBitrate: 128, includeVideo: false, includeAudio: true,
      resolution: "1080p", width: 1920, height: 1080, framerate: 30,
      videoBitrate: 0, videoCodec: "h264", crf: 23, keyframeInterval: 250,
      pixelFormat: "yuv420p", fastStart: false, scope: "entire",
    },
  },
  {
    id: "ogg-vorbis",
    name: "OGG Vorbis",
    platform: "Open Source",
    description: "Free open audio format (Vorbis)",
    icon: "🔓",
    category: "audio",
    popular: false,
    settings: {
      format: "ogg", audioCodec: "vorbis", sampleRate: 48000, channels: 2,
      audioBitrate: 256, includeVideo: false, includeAudio: true,
      resolution: "1080p", width: 1920, height: 1080, framerate: 30,
      videoBitrate: 0, videoCodec: "h264", crf: 23, keyframeInterval: 250,
      pixelFormat: "yuv420p", fastStart: false, scope: "entire",
    },
  },
];

export function getPresetById(id: string): ExportPresetDefinition | undefined {
  return EXPORT_PRESETS.find((p) => p.id === id);
}

export function getPresetsByCategory(category: string): ExportPresetDefinition[] {
  return EXPORT_PRESETS.filter((p) => p.category === category);
}
