import type { TextPreset } from "@/types/editor";

export const TEXT_PRESETS: TextPreset[] = [
  // ── Titles ──
  {
    id: "modern-title",
    name: "Modern Title",
    description: "Clean bold modern title",
    category: "title",
    preview: "Modern\nTitle",
    style: {
      fontFamily: "'Inter', sans-serif", fontSize: 72, color: "#ffffff", alignment: "center",
      bold: true, italic: false, underline: false, uppercase: false, lineHeight: 1.1, letterSpacing: -1,
      background: "", backgroundOpacity: 0, strokeColor: "#000", strokeWidth: 0,
      shadowColor: "rgba(0,0,0,0.5)", shadowBlur: 10, shadowOffsetX: 0, shadowOffsetY: 4,
      borderRadius: 0, paddingX: 24, paddingY: 12,
    },
    animation: { type: "fade", duration: 0.6, delay: 0, stagger: 0 },
  },
  {
    id: "classic-title",
    name: "Classic Serif",
    description: "Elegant serif title",
    category: "title",
    preview: "Classic\nTitle",
    style: {
      fontFamily: "'Playfair Display', serif", fontSize: 64, color: "#ffffff", alignment: "center",
      bold: true, italic: true, underline: false, uppercase: false, lineHeight: 1.15, letterSpacing: 0.5,
      background: "", backgroundOpacity: 0, strokeColor: "#000", strokeWidth: 0,
      shadowColor: "rgba(0,0,0,0.4)", shadowBlur: 6, shadowOffsetX: 0, shadowOffsetY: 3,
      borderRadius: 0, paddingX: 20, paddingY: 10,
    },
    animation: { type: "scale", duration: 0.7, delay: 0, stagger: 0 },
  },
  {
    id: "neon-title",
    name: "Neon Glow",
    description: "Bright neon sign effect",
    category: "title",
    preview: "NEON\nTITLE",
    style: {
      fontFamily: "'Monument Extended', sans-serif", fontSize: 60, color: "#00fff5", alignment: "center",
      bold: true, italic: false, underline: false, uppercase: true, lineHeight: 1.1, letterSpacing: 6,
      background: "", backgroundOpacity: 0, strokeColor: "#00fff5", strokeWidth: 1,
      shadowColor: "#00fff5", shadowBlur: 20, shadowOffsetX: 0, shadowOffsetY: 0,
      borderRadius: 0, paddingX: 24, paddingY: 12,
    },
    animation: { type: "glow", duration: 1, delay: 0, stagger: 0 },
  },
  {
    id: "bold-impact",
    name: "Bold Impact",
    description: "Heavy bold uppercase impact",
    category: "title",
    preview: "IMPACT",
    style: {
      fontFamily: "'Anton', sans-serif", fontSize: 80, color: "#ffffff", alignment: "center",
      bold: true, italic: false, underline: false, uppercase: true, lineHeight: 1, letterSpacing: 2,
      background: "", backgroundOpacity: 0, strokeColor: "#000", strokeWidth: 3,
      shadowColor: "rgba(0,0,0,0.6)", shadowBlur: 8, shadowOffsetX: 0, shadowOffsetY: 4,
      borderRadius: 0, paddingX: 20, paddingY: 8,
    },
    animation: { type: "pop", duration: 0.4, delay: 0, stagger: 0 },
  },
  {
    id: "vintage-poster",
    name: "Vintage Poster",
    description: "Retro poster aesthetic",
    category: "title",
    preview: "VINTAGE",
    style: {
      fontFamily: "'DM Serif Display', serif", fontSize: 56, color: "#f5d742", alignment: "center",
      bold: false, italic: false, underline: false, uppercase: true, lineHeight: 1, letterSpacing: 4,
      background: "#1a1410", backgroundOpacity: 0.8, strokeColor: "#8b6914", strokeWidth: 1,
      shadowColor: "rgba(0,0,0,0.6)", shadowBlur: 0, shadowOffsetX: 3, shadowOffsetY: 3,
      borderRadius: 0, paddingX: 32, paddingY: 16,
    },
    animation: { type: "slide-up", duration: 0.8, delay: 0, stagger: 0 },
  },
  {
    id: "minimal-title",
    name: "Minimal Light",
    description: "Clean minimal with thin weight",
    category: "title",
    preview: "Minimal",
    style: {
      fontFamily: "'Inter', sans-serif", fontSize: 52, color: "#ffffff", alignment: "center",
      bold: false, italic: false, underline: false, uppercase: false, lineHeight: 1.2, letterSpacing: 4,
      background: "", backgroundOpacity: 0, strokeColor: "#000", strokeWidth: 0,
      shadowColor: "rgba(0,0,0,0.3)", shadowBlur: 4, shadowOffsetX: 0, shadowOffsetY: 2,
      borderRadius: 0, paddingX: 16, paddingY: 8,
    },
    animation: { type: "fade", duration: 0.8, delay: 0, stagger: 0 },
  },
  {
    id: "gradient-title",
    name: "Gradient Title",
    description: "Vibrant gradient text",
    category: "title",
    preview: "GRADIENT",
    style: {
      fontFamily: "'Unbounded', sans-serif", fontSize: 60, color: "#ffffff", alignment: "center",
      bold: true, italic: false, underline: false, uppercase: true, lineHeight: 1.1, letterSpacing: 3,
      background: "linear-gradient(135deg, #f093fb, #f5576c, #4facfe)", backgroundOpacity: 1,
      strokeColor: "#fff", strokeWidth: 0,
      shadowColor: "rgba(240,147,251,0.4)", shadowBlur: 16, shadowOffsetX: 0, shadowOffsetY: 0,
      borderRadius: 0, paddingX: 24, paddingY: 12,
    },
    animation: { type: "slide-down", duration: 0.6, delay: 0, stagger: 0 },
  },
  {
    id: "typewriter-title",
    name: "Typewriter",
    description: "Typewriter typing effect",
    category: "title",
    preview: "Hello World",
    style: {
      fontFamily: "'Space Grotesk', sans-serif", fontSize: 44, color: "#ffffff", alignment: "center",
      bold: false, italic: false, underline: false, uppercase: false, lineHeight: 1.3, letterSpacing: 1,
      background: "", backgroundOpacity: 0, strokeColor: "#000", strokeWidth: 0,
      shadowColor: "rgba(0,0,0,0.3)", shadowBlur: 4, shadowOffsetX: 0, shadowOffsetY: 2,
      borderRadius: 0, paddingX: 16, paddingY: 8,
    },
    animation: { type: "typewriter", duration: 1.5, delay: 0, stagger: 0.03 },
  },

  // ── Lower Thirds ──
  {
    id: "lower-third-modern",
    name: "Modern Lower Third",
    description: "Sleek lower third bar",
    category: "lower-third",
    preview: "Name\nTitle",
    style: {
      fontFamily: "'Inter', sans-serif", fontSize: 28, color: "#ffffff", alignment: "left",
      bold: true, italic: false, underline: false, uppercase: false, lineHeight: 1.3, letterSpacing: 0,
      background: "linear-gradient(90deg, #4facfe 0%, transparent 100%)", backgroundOpacity: 0.85,
      strokeColor: "#000", strokeWidth: 0,
      shadowColor: "rgba(0,0,0,0.4)", shadowBlur: 4, shadowOffsetX: 0, shadowOffsetY: 2,
      borderRadius: 0, paddingX: 20, paddingY: 8,
    },
    animation: { type: "slide-left", duration: 0.5, delay: 0, stagger: 0 },
  },
  {
    id: "lower-third-minimal",
    name: "Minimal Lower Third",
    description: "Clean minimal name tag",
    category: "lower-third",
    preview: "Jane Doe",
    style: {
      fontFamily: "'DM Sans', sans-serif", fontSize: 24, color: "#ffffff", alignment: "left",
      bold: false, italic: false, underline: false, uppercase: false, lineHeight: 1.4, letterSpacing: 0.5,
      background: "rgba(0,0,0,0.5)", backgroundOpacity: 0.7,
      strokeColor: "#000", strokeWidth: 0,
      shadowColor: "", shadowBlur: 0, shadowOffsetX: 0, shadowOffsetY: 0,
      borderRadius: 4, paddingX: 14, paddingY: 6,
    },
    animation: { type: "slide-up", duration: 0.4, delay: 0, stagger: 0 },
  },

  // ── Subtitles ──
  {
    id: "subtitle-standard",
    name: "Standard Subtitle",
    description: "Clean readable subtitles",
    category: "subtitle",
    preview: "This is a subtitle",
    style: {
      fontFamily: "'Inter', sans-serif", fontSize: 22, color: "#ffffff", alignment: "center",
      bold: false, italic: false, underline: false, uppercase: false, lineHeight: 1.4, letterSpacing: 0.5,
      background: "rgba(0,0,0,0.6)", backgroundOpacity: 0.8,
      strokeColor: "#000", strokeWidth: 1,
      shadowColor: "rgba(0,0,0,0.5)", shadowBlur: 2, shadowOffsetX: 0, shadowOffsetY: 1,
      borderRadius: 4, paddingX: 16, paddingY: 4,
    },
    animation: { type: "fade", duration: 0.3, delay: 0, stagger: 0 },
  },
  {
    id: "subtitle-bold",
    name: "Bold Subtitles",
    description: "High visibility bold subtitles",
    category: "subtitle",
    preview: "BOLD SUBTITLE",
    style: {
      fontFamily: "'Oswald', sans-serif", fontSize: 26, color: "#ffffff", alignment: "center",
      bold: true, italic: false, underline: false, uppercase: true, lineHeight: 1.3, letterSpacing: 1,
      background: "rgba(0,0,0,0.7)", backgroundOpacity: 0.85,
      strokeColor: "#000", strokeWidth: 1,
      shadowColor: "rgba(0,0,0,0.6)", shadowBlur: 4, shadowOffsetX: 0, shadowOffsetY: 2,
      borderRadius: 2, paddingX: 16, paddingY: 4,
    },
    animation: { type: "fade", duration: 0.25, delay: 0, stagger: 0 },
  },
  {
    id: "subtitle-elegant",
    name: "Elegant Subtitles",
    description: "Elegant serif subtitles",
    category: "subtitle",
    preview: "Elegant subtitles",
    style: {
      fontFamily: "'Lora', serif", fontSize: 20, color: "#f0f0f0", alignment: "center",
      bold: false, italic: true, underline: false, uppercase: false, lineHeight: 1.5, letterSpacing: 0.3,
      background: "linear-gradient(90deg, transparent, rgba(0,0,0,0.5), transparent)", backgroundOpacity: 0.7,
      strokeColor: "#000", strokeWidth: 0.5,
      shadowColor: "rgba(0,0,0,0.4)", shadowBlur: 3, shadowOffsetX: 0, shadowOffsetY: 1,
      borderRadius: 0, paddingX: 24, paddingY: 6,
    },
    animation: { type: "fade", duration: 0.4, delay: 0, stagger: 0 },
  },

  // ── Callouts ──
  {
    id: "callout-top-left",
    name: "Top Left Callout",
    description: "Information corner callout",
    category: "callout",
    preview: "DID YOU KNOW?",
    style: {
      fontFamily: "'Poppins', sans-serif", fontSize: 20, color: "#4facfe", alignment: "left",
      bold: true, italic: false, underline: false, uppercase: true, lineHeight: 1.3, letterSpacing: 2,
      background: "rgba(0,0,0,0.6)", backgroundOpacity: 0.7,
      strokeColor: "#000", strokeWidth: 0,
      shadowColor: "rgba(0,0,0,0.3)", shadowBlur: 4, shadowOffsetX: 0, shadowOffsetY: 2,
      borderRadius: 6, paddingX: 14, paddingY: 6,
    },
    animation: { type: "slide-down", duration: 0.4, delay: 0, stagger: 0 },
  },
  {
    id: "callout-badge",
    name: "Badge Callout",
    description: "Rounded badge style",
    category: "callout",
    preview: "NEW",
    style: {
      fontFamily: "'Inter', sans-serif", fontSize: 14, color: "#ffffff", alignment: "center",
      bold: true, italic: false, underline: false, uppercase: true, lineHeight: 1, letterSpacing: 2,
      background: "#f5576c", backgroundOpacity: 1,
      strokeColor: "#000", strokeWidth: 0,
      shadowColor: "rgba(245,87,108,0.4)", shadowBlur: 8, shadowOffsetX: 0, shadowOffsetY: 0,
      borderRadius: 20, paddingX: 12, paddingY: 4,
    },
    animation: { type: "bounce", duration: 0.5, delay: 0, stagger: 0 },
  },

  // ── Credits ──
  {
    id: "credit-scroll",
    name: "Credit Scroll",
    description: "End credits style",
    category: "credit",
    preview: "Directed by\nName Here",
    style: {
      fontFamily: "'Montserrat', sans-serif", fontSize: 36, color: "#ffffff", alignment: "center",
      bold: false, italic: false, underline: false, uppercase: false, lineHeight: 1.6, letterSpacing: 2,
      background: "", backgroundOpacity: 0, strokeColor: "#000", strokeWidth: 0,
      shadowColor: "rgba(0,0,0,0.4)", shadowBlur: 6, shadowOffsetX: 0, shadowOffsetY: 3,
      borderRadius: 0, paddingX: 16, paddingY: 8,
    },
    animation: { type: "slide-up", duration: 1, delay: 0, stagger: 0.1 },
  },
  {
    id: "credit-minimal",
    name: "Minimal Credit",
    description: "Simple credit line",
    category: "credit",
    preview: "A Film By",
    style: {
      fontFamily: "'Inter', sans-serif", fontSize: 28, color: "#aaa", alignment: "center",
      bold: false, italic: false, underline: false, uppercase: true, lineHeight: 1.4, letterSpacing: 4,
      background: "", backgroundOpacity: 0, strokeColor: "#000", strokeWidth: 0,
      shadowColor: "rgba(0,0,0,0.3)", shadowBlur: 3, shadowOffsetX: 0, shadowOffsetY: 2,
      borderRadius: 0, paddingX: 16, paddingY: 8,
    },
    animation: { type: "fade", duration: 0.8, delay: 0, stagger: 0 },
  },

  // ── Lyrics ──
  {
    id: "lyric-karaoke",
    name: "Karaoke Style",
    description: "Bold centered lyrics",
    category: "lyric",
    preview: "Never gonna\ngive you up",
    style: {
      fontFamily: "'Poppins', sans-serif", fontSize: 36, color: "#ffffff", alignment: "center",
      bold: true, italic: false, underline: false, uppercase: false, lineHeight: 1.3, letterSpacing: 1,
      background: "", backgroundOpacity: 0, strokeColor: "#000", strokeWidth: 1,
      shadowColor: "rgba(0,0,0,0.5)", shadowBlur: 6, shadowOffsetX: 0, shadowOffsetY: 3,
      borderRadius: 0, paddingX: 16, paddingY: 8,
    },
    animation: { type: "fade", duration: 0.4, delay: 0, stagger: 0 },
  },
  {
    id: "lyric-gradient",
    name: "Gradient Lyric",
    description: "Vibrant gradient lyrics",
    category: "lyric",
    preview: "Song\nLyrics",
    style: {
      fontFamily: "'DM Sans', sans-serif", fontSize: 40, color: "#ffffff", alignment: "center",
      bold: true, italic: false, underline: false, uppercase: false, lineHeight: 1.2, letterSpacing: 0,
      background: "linear-gradient(135deg, #667eea, #764ba2)", backgroundOpacity: 1,
      strokeColor: "#fff", strokeWidth: 0,
      shadowColor: "rgba(102,126,234,0.4)", shadowBlur: 12, shadowOffsetX: 0, shadowOffsetY: 0,
      borderRadius: 8, paddingX: 24, paddingY: 12,
    },
    animation: { type: "wave", duration: 0.8, delay: 0, stagger: 0.05 },
  },
  {
    id: "title-watermark",
    name: "Watermark",
    description: "Subtle corner watermark",
    category: "callout",
    preview: "© 2026",
    style: {
      fontFamily: "'Inter', sans-serif", fontSize: 14, color: "rgba(255,255,255,0.5)", alignment: "right",
      bold: false, italic: false, underline: false, uppercase: false, lineHeight: 1, letterSpacing: 1,
      background: "", backgroundOpacity: 0, strokeColor: "#000", strokeWidth: 0,
      shadowColor: "", shadowBlur: 0, shadowOffsetX: 0, shadowOffsetY: 0,
      borderRadius: 0, paddingX: 8, paddingY: 4,
    },
    animation: { type: "none", duration: 0, delay: 0, stagger: 0 },
  },
  {
    id: "social-handle",
    name: "Social Handle",
    description: "Instagram/TikTok style handle",
    category: "callout",
    preview: "@username",
    style: {
      fontFamily: "'Montserrat', sans-serif", fontSize: 18, color: "#ffffff", alignment: "left",
      bold: true, italic: false, underline: false, uppercase: false, lineHeight: 1, letterSpacing: 0,
      background: "linear-gradient(90deg, #f58529, #dd2a7b)", backgroundOpacity: 0.9,
      strokeColor: "#000", strokeWidth: 0,
      shadowColor: "rgba(0,0,0,0.3)", shadowBlur: 3, shadowOffsetX: 0, shadowOffsetY: 2,
      borderRadius: 4, paddingX: 10, paddingY: 4,
    },
    animation: { type: "slide-left", duration: 0.4, delay: 0, stagger: 0 },
  },
  {
    id: "countdown-number",
    name: "Countdown Number",
    description: "Big centered number",
    category: "title",
    preview: "3",
    style: {
      fontFamily: "'Anton', sans-serif", fontSize: 160, color: "#ffffff", alignment: "center",
      bold: true, italic: false, underline: false, uppercase: false, lineHeight: 1, letterSpacing: 0,
      background: "", backgroundOpacity: 0, strokeColor: "#000", strokeWidth: 4,
      shadowColor: "rgba(0,0,0,0.6)", shadowBlur: 12, shadowOffsetX: 0, shadowOffsetY: 6,
      borderRadius: 0, paddingX: 0, paddingY: 0,
    },
    animation: { type: "scale", duration: 0.5, delay: 0, stagger: 0 },
  },
  {
    id: "quote-overlay",
    name: "Quote Overlay",
    description: "Elegant quote style",
    category: "callout",
    preview: "\"The only\nlimit is you.\"",
    style: {
      fontFamily: "'Merriweather', serif", fontSize: 32, color: "#ffffff", alignment: "center",
      bold: false, italic: true, underline: false, uppercase: false, lineHeight: 1.4, letterSpacing: 0.5,
      background: "rgba(0,0,0,0.4)", backgroundOpacity: 0.5,
      strokeColor: "#000", strokeWidth: 0,
      shadowColor: "rgba(0,0,0,0.4)", shadowBlur: 6, shadowOffsetX: 0, shadowOffsetY: 3,
      borderRadius: 0, paddingX: 32, paddingY: 20,
    },
    animation: { type: "fade", duration: 0.8, delay: 0, stagger: 0 },
  },
];

export function getPresetById(id: string): TextPreset | undefined {
  return TEXT_PRESETS.find((p) => p.id === id);
}

export function getPresetsByCategory(category: string): TextPreset[] {
  return TEXT_PRESETS.filter((p) => p.category === category);
}
